'''
Constants Information File

Created by Pierce Alvir and Steven Santamorena

'''

#X Constants
X_STEP_PIN = 18
X_DIR_PIN = 23
X_EN_PIN = 24
X_LIMIT = 1200
X_STEP_DELAY = 0.001

#Y Constants
Y_STEP_PIN = 12
Y_DIR_PIN = 5
Y_EN_PIN = 6
Y_LIMIT = 4800
Y_STEP_DELAY = 0.002

#Z Constants
Z_STEP_PIN = 16
Z_DIR_PIN = 20
Z_EN_PIN = 21
Z_LIMIT = 4000
Z_STEP_DELAY = 0.001

#Head Constants
HEAD_STEP_PIN = 13
HEAD_DIR_PIN = 19
HEAD_EN_PIN = 26
HEAD_VACUUM_PIN = 25
HEAD_MICROSTEP_MODE = 4
HEAD_STEPS_PER_UL = 150/200
HEAD_STEP_DELAY = 0.008
HEAD_STEP_SLEEP_TIME = 0.05
HEAD_MAX_UL = 200
HEAD_LIMIT = 275
UL_CORRECTION_FACTOR = 0.9
UL_CORRECTION_OFFSET = 2

#Carousel Constants
CAROUSEL_STEP_PIN = 17
CAROUSEL_DIR_PIN = 27
CAROUSEL_EN_PIN = 22
CAROUSEL_VIAL = 8
CAROUSEL_STEP_DELAY = 0.006
CAROUSEL_STEP_SLEEP_TIME = 0.0001 #not sure if this gets used but it was in carousel file



